spring.application.name=JobPortal


#database configuration
spring.datasource.url= jdbc:mysql://localhost:3306/jobportal
spring.datasource.username=root
spring.datasource.password = Divyansh@6069

#hibernate configuration
spring.jpa.hibernate.ddl-auto= update
spring.jpa.show-sql=true
